# Generated by Django 3.2.3 on 2021-05-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dozen',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gamenumber',
            name='author',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='author',
        ),
    ]
